### ISSUE TITLE
When jobname+matrix length exceeds 97 characters the job fails 

### ISSUE THREAD

**Issue by c3charvat** [qoomon/actions--context#44]
With a jobname + martrix that exceeds  97 characters GHA truncates the job name/ inputs and adds an ellipses. This causes this job to fail

**Comment by qoomon** [comment]
@c3charvat do you mean the job name field of the list job api response is truncated?

**Comment by c3charvat** [comment]
@qoomon its sadly behind a corporate wall. I have a fork out with actions on it that replicate the issue and a solution (i think)

**Comment by c3charvat** [comment]
@qoomon  PR is out

**Comment by qoomon** [comment]
I'll make a release tomorrow

**Comment by c3charvat** [comment]
@qoomon Is you linked email address good? Id like to stay in touch until i can see if i can get the desired changes pushed through on actions/runner. I added more content at the request of someone on the issue: https://github.com/daleyjem/gh-job-id/issues/5

**Comment by qoomon** [comment]
> Is you linked email address good? 
Should work. Otherwise have a look at https://qoo.monster for several contact options.

**Comment by qoomon** [comment]
> I'll make a release tomorrow

feel free to try version `v2.1.0` or `v2`
